### PR TITLE
Update EnergyAttribute.java

### PR DESCRIPTION
**Pull request by falseresync**

### CODE REVIEW

**Comment by Juuxel** [comment]
Isn't the other amount more useful to know? I'd suggest correcting the implementation.

**Review by Pannoniae — APPROVED** [review]

**Comment by falseresync** [comment]
No difference actually

**Review by Juuxel — COMMENTED** [review]
See my other comment.

**Comment by falseresync** [comment]
You have the transferred amount from this &
You have the amount you wanted to transfer initially.
So, what's the problem? I think it is unnecessary to include this minus operation into the API

**Comment by Juuxel** [comment]
Hm, true.

**Review by Juuxel — APPROVED** [review]

**Comment by LemmaEOF** [comment]
This functionality was a change Falk and I agreed on a couple months back, but forgot to update the javadocs for. This fits with the standard for partial transfers that's been in basically every item, fluid, and energy transfer API that has partial support.

**Pull request merged**
